#更改springboot端口号(默认是8080)
server:
  port: 80

spring:
  profiles:
    active: dev

---
#development environment
spring:
  profiles: dev

---
#test environment
spring:
  profiles: test

---
#production environment
spring:
  profiles: prod
